[server]
style = "home/aliaks/.config/swayosd/style.css"
top_margin = 0.5

# show_percentage = true
# max_volume = 150
# playerctl_format = "{artist} - {title}"
## available values:
## artist, albumArtist, title, album, trackNumber, discNumber, autoRating

[client]
