source = ~/.config/hypr/colors/gruvbox.conf
general {
    hide_cursor = true
}

# Fingerprint settings
auth {
    fingerprint:enabled = true
    fingerprint:ready_message = or Scan fingerprint
    fingerprint:present_message = Scanning...
}

# Wallpaper
background { 
    path = /home/aliaks/Pictures/Wallpapers/Gruvbox/minimalistic/gruv-portal-cake.png
    blur_passes = 2
    blur_size = 5
}

# Password input
input-field {
    monitor = 
    size = 200, 50
    outline_thickness = 3
    rounding = 10
    inner_color = $background
    outer_color = $border_lock
    font_color = rgb(ffffff)
    fade_on_empty = false
    placeholder_text =
    capslock_color = rgb(255,0,255) 
    position = 0, -50
}

# Profile picture
image {
    monitor =
    path = /home/aliaks/Pictures/kitty.png
    size = 175
    border_size = 4
    #border_color = rgb(dd4451)
    border_color = $border_lock
    position = 0, 110
}

# User greeting
label {
    monitor =
    #text = Hi, Aliaksandr.<br/>The time is $TIME.
    text = Hi, Aliaksandr.
    text_align = center
    font_size = 50
    font_family = DejaVuSerif Bold

    shadow_passes = 3
    shadow_size = 2

    position = 0, 900
    halign = center
}

# Time Label
label {
    monitor = 
    text = $TIME.
    text_align = center
    font_size = 100
    font_family = DejaVuSerif Bold

    shadow_passes = 3
    shadow_size = 2

    position = 15, 750
    halign = center
}

# Fingerprint Message
label {
    monitor =
    text = $FPRINTPROMPT
    font_size = 15

    position = 0, -110
    halign = center
    valign = center
}

# Battery Percentage
label {
    monitor = 
    text = cmd[update:1000] echo " $(cat /sys/class/power_supply/BAT0/capacity)%"
    position = -20, -20 
    halign = right
    valign = top
}
